#!/usr/bin/env bash
# Generate serving/llama-swap.rendered.yaml from serving/models.manifest,
# honoring serving/models.profile (if present) and resolving local GGUF paths.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
MANIFEST="serving/models.manifest"
PROFILE="serving/models.profile"
OUT="serving/llama-swap.rendered.yaml"

is_active() {  # active if profiled OR already downloaded (no profile file => all)
  [[ ! -f "$PROFILE" ]] && return 0
  grep -qx "$1" "$PROFILE" && return 0
  [[ -n "$(find "models/$1" -name '*.gguf' -type f 2>/dev/null | head -1)" ]]
}

first_gguf() {  # first shard of a multi-part GGUF, or the single .gguf
  local f
  f=$(find "models/$1" -name "*-00001-of-*.gguf" -type f 2>/dev/null | head -1)
  [[ -z "$f" ]] && f=$(find "models/$1" -name "*.gguf" -type f 2>/dev/null | sort | head -1)
  echo "$f"
}

TMP="$(mktemp)"
big_members=(); resident_members=(); missing=0

cat > "$TMP" <<'EOF'
# GENERATED by bootstrap/render-config.sh — edit serving/models.manifest instead.
#
# llama-swap front door for BOTH engines:
#   Claude Code -> Anthropic  http://127.0.0.1:9099/v1/messages
#   OpenCode    -> OpenAI     http://127.0.0.1:9099/v1/chat/completions

# listen address is a CLI flag (--listen 127.0.0.1:9099), set by service.sh
healthCheckTimeout: 900          # big models need minutes to load from SSD
logLevel: info

macros:
  # If your llama.cpp build rejects "-fa on", change to "--flash-attn".
  common: >
    --host 127.0.0.1 --port ${PORT}
    --n-gpu-layers 999 -fa on --jinja
    --cache-type-k q8_0 --cache-type-v q8_0

models:
EOF

while IFS='|' read -r name repo include slot ctx flags; do
  name="$(echo "$name" | xargs)"; slot="$(echo "$slot" | xargs)"
  ctx="$(echo "$ctx" | xargs)";   flags="$(echo "${flags:-}" | xargs)"
  [[ -z "$name" ]] && continue
  is_active "$name" || { echo "  (profile) skipping $name"; continue; }
  path="$(first_gguf "$name")"
  if [[ -z "$path" ]]; then
    echo "MISSING: models/$name — run 'make models' (or ./install)"; missing=1; continue
  fi
  echo "  $name -> $path"
  case "$slot" in
    big)
      big_members+=("$name")
      cat >> "$TMP" <<EOF
  "$name":
    cmd: |
      llama-server \${common}
      -m $ROOT/$path
      --ctx-size $ctx --parallel 1
      $flags
    ttl: 0
EOF
      ;;
    fast)
      resident_members+=("$name")
      cat >> "$TMP" <<EOF
  "$name":
    cmd: |
      llama-server \${common}
      -m $ROOT/$path
      --ctx-size $ctx --parallel 2 --mlock
      $flags
    ttl: 0
EOF
      ;;
    embed)
      resident_members+=("$name")
      cat >> "$TMP" <<EOF
  "$name":
    cmd: |
      llama-server --host 127.0.0.1 --port \${PORT}
      -m $ROOT/$path
      --n-gpu-layers 999 --embeddings --pooling last
      --ctx-size $ctx --mlock
    ttl: 0
EOF
      ;;
    *) echo "ERROR: unknown slot '$slot' for $name"; exit 1 ;;
  esac
done < <(grep -Ev '^\s*(#|$)' "$MANIFEST")

[[ $missing -eq 1 ]] && { echo "ERROR: models missing; not rendering."; rm -f "$TMP"; exit 1; }
[[ ${#resident_members[@]} -eq 0 ]] && { echo "ERROR: fast/embed models are required."; rm -f "$TMP"; exit 1; }

{
  echo ""
  echo "groups:"
  if [[ ${#big_members[@]} -gt 0 ]]; then
    echo "  big:"
    echo "    swap: true                   # only one big model resident at a time"
    echo "    exclusive: false             # do NOT evict the resident group when swapping"
    echo "    members:"
    for mdl in "${big_members[@]}"; do echo "      - \"$mdl\""; done
  fi
  echo "  resident:"
  echo "    swap: false                  # members run simultaneously..."
  echo "    exclusive: false"
  echo "    persistent: true             # ...and are never evicted by other groups"
  echo "    members:"
  for mdl in "${resident_members[@]}"; do echo "      - \"$mdl\""; done
} >> "$TMP"

mv "$TMP" "$OUT"
echo "Rendered $OUT (${#big_members[@]} big, ${#resident_members[@]} resident)"
