#!/usr/bin/env bash
# The Cursor-like IDE for the appliance: VSCodium (telemetry-free VS Code) with
# Continue (chat / inline edit / autocomplete) and Roo Code (agentic side panel),
# all pointed at the local llama-swap endpoint. Fully offline after install.
#
#   bash connectors/ide/setup-ide.sh install    cask + pinned .vsix + configs
#   bash connectors/ide/setup-ide.sh launch     open the IDE on this repo
#
# Cursor-parity map: chat with codebase -> Continue chat (Cmd+L); inline edits ->
# Continue edit (Cmd+I); tab autocomplete -> Continue (fast lane model); agent
# composer -> Roo Code panel (reads/writes files, runs terminal, plan/act).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VSIX_DIR="$ROOT/incoming/vsix"

fetch_vsix() {  # fetch_vsix <namespace> <name>
  local meta url ver
  meta="$(curl -sf --proto '=https' "https://open-vsx.org/api/$1/$2/latest")"
  url="$(echo "$meta" | jq -r '.files.download')"
  ver="$(echo "$meta" | jq -r '.version')"
  echo "==> $1.$2 $ver"
  curl -sfL --proto '=https' -o "$VSIX_DIR/$1.$2-$ver.vsix" "$url"
  echo "$VSIX_DIR/$1.$2-$ver.vsix"
}

write_continue_config() {
  mkdir -p "$HOME/.continue"
  cat > "$HOME/.continue/config.yaml" <<'EOF'
# GENERATED by setup-ide.sh — Continue wired to the local llama-swap endpoint.
name: SentiVue Oracle
version: 1.0.0
models:
  - name: Qwen3 Coder 480B (primary)
    provider: openai
    model: qwen3-coder-480b
    apiBase: http://127.0.0.1:9099/v1
    apiKey: oracle-local
    roles: [chat, edit, apply]
  - name: Kimi K2 Thinking (deep reasoning)
    provider: openai
    model: kimi-k2-thinking
    apiBase: http://127.0.0.1:9099/v1
    apiKey: oracle-local
    roles: [chat]
  - name: Qwen3 Coder 30B (autocomplete)
    provider: openai
    model: qwen3-coder-30b
    apiBase: http://127.0.0.1:9099/v1
    apiKey: oracle-local
    roles: [autocomplete]
  - name: Qwen3 Embedding
    provider: openai
    model: qwen3-embedding-4b
    apiBase: http://127.0.0.1:9099/v1
    apiKey: oracle-local
    roles: [embed]
EOF
  echo "==> wrote ~/.continue/config.yaml"
}

write_codium_settings() {
  local dir="$HOME/Library/Application Support/VSCodium/User"
  mkdir -p "$dir"
  if [[ ! -f "$dir/settings.json" ]]; then
    cat > "$dir/settings.json" <<'EOF'
{
  "telemetry.telemetryLevel": "off",
  "update.mode": "none",
  "extensions.autoUpdate": false,
  "extensions.autoCheckUpdates": false,
  "workbench.colorTheme": "Default Dark Modern",
  "editor.inlineSuggest.enabled": true,
  "continue.enableTabAutocomplete": true
}
EOF
    echo "==> wrote VSCodium settings (telemetry off, updates off)"
  fi
}

case "${1:-launch}" in
  install)
    command -v codium >/dev/null || { echo "==> brew install --cask vscodium"; brew install --cask vscodium; }
    mkdir -p "$VSIX_DIR"
    cont="$(fetch_vsix Continue continue | tail -1)"
    roo="$(fetch_vsix RooVeterinaryInc roo-cline | tail -1)"
    codium --install-extension "$cont" --force
    codium --install-extension "$roo"  --force
    write_continue_config
    write_codium_settings
    echo
    echo "IDE ready. One-time Roo Code setup (stores its own config):"
    echo "  panel -> settings -> API Provider: OpenAI Compatible"
    echo "  Base URL: http://127.0.0.1:9099/v1   API Key: oracle-local"
    echo "  Model: qwen3-coder-480b"
    echo "Launch with: oracle ide"
    ;;
  launch)
    command -v codium >/dev/null || { echo "IDE not installed — run: bash connectors/ide/setup-ide.sh install"; exit 1; }
    exec codium "$ROOT"
    ;;
  *) echo "usage: setup-ide.sh {install|launch}"; exit 1 ;;
esac
