# Windows twin of setup-ide.sh: the Cursor-like IDE on local models.
# VSCodium (telemetry-free VS Code) + Continue (chat/edit/autocomplete) +
# Roo Code (agentic panel), all pointed at llama-swap on 127.0.0.1:9099.
#
#   powershell -File connectors\ide\setup-ide.ps1 install
#   powershell -File connectors\ide\setup-ide.ps1 launch
param([Parameter(Position = 0)][string]$Cmd = "launch")
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)

function Find-Codium {
    $c = Get-Command codium -ErrorAction SilentlyContinue
    if ($c) { return $c.Source }
    $candidates = @(
        "$env:LOCALAPPDATA\Programs\VSCodium\bin\codium.cmd",
        "$env:ProgramFiles\VSCodium\bin\codium.cmd"
    )
    foreach ($p in $candidates) { if (Test-Path $p) { return $p } }
    return $null
}

switch ($Cmd) {
    "install" {
        $codium = Find-Codium
        if (-not $codium) {
            Write-Host "==> installing VSCodium (winget)"
            winget install --id VSCodium.VSCodium -e --silent --accept-package-agreements --accept-source-agreements
            $codium = Find-Codium
            if (-not $codium) { Write-Host "ERROR: VSCodium installed but codium CLI not found - reopen the terminal and re-run"; exit 1 }
        }
        $vsix = Join-Path $Root "incoming\vsix"
        New-Item -ItemType Directory -Force -Path $vsix | Out-Null
        # Continue ships native modules (sqlite3, lancedb, onnx) - must take the
        # win32-x64 build, not the universal one, or activation fails.
        foreach ($ext in @(@("Continue", "continue", "win32-x64"), @("RooVeterinaryInc", "roo-cline", ""))) {
            $ns = $ext[0]; $name = $ext[1]; $plat = $ext[2]
            $meta = $null
            if ($plat) {
                try { $meta = Invoke-RestMethod -Uri "https://open-vsx.org/api/$ns/$name/$plat/latest" } catch { $meta = $null }
            }
            if (-not $meta) { $meta = Invoke-RestMethod -Uri "https://open-vsx.org/api/$ns/$name/latest" }
            $tag = if ($plat) { "$plat-" } else { "" }
            $file = Join-Path $vsix "$ns.$name-$tag$($meta.version).vsix"
            Write-Host "==> $ns.$name $($meta.version) $plat"
            if (-not (Test-Path $file)) { Invoke-WebRequest -Uri $meta.files.download -OutFile $file }
            & $codium --install-extension $file --force | Out-Null
        }
        # Open VSX builds of Continue ship WITHOUT the ripgrep binary, so the
        # extension dies on activation with "Could not find ripgrep binary".
        # Graft VSCodium's own rg.exe into the extension to fix it.
        $contExt = Get-ChildItem "$env:USERPROFILE\.vscode-oss\extensions" -Directory -ErrorAction SilentlyContinue |
            Where-Object Name -match "^continue\.continue-" | Sort-Object Name -Descending | Select-Object -First 1
        if ($contExt) {
            $rgDest = Join-Path $contExt.FullName "out\node_modules\@vscode\ripgrep\bin"
            if (-not (Test-Path (Join-Path $rgDest "rg.exe"))) {
                $codiumRoot = Split-Path -Parent (Split-Path -Parent $codium)  # ...\VSCodium from ...\VSCodium\bin\codium.cmd
                $rgSrc = Get-ChildItem (Join-Path $codiumRoot "resources\app\node_modules\@vscode") -Recurse -Filter "rg.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
                if ($rgSrc) {
                    New-Item -ItemType Directory -Force -Path $rgDest | Out-Null
                    Copy-Item $rgSrc.FullName (Join-Path $rgDest "rg.exe") -Force
                    Write-Host "==> grafted ripgrep into Continue (Open VSX build ships without it)"
                }
            }
        }
        # Continue -> local llama-swap (same config content as the Mac twin)
        $cont = Join-Path $env:USERPROFILE ".continue"
        New-Item -ItemType Directory -Force -Path $cont | Out-Null
        @'
# GENERATED by setup-ide.ps1 - Continue wired to the local llama-swap endpoint.
name: SentiVue Oracle
version: 1.0.0
models:
  - name: Primary coder (local)
    provider: openai
    model: qwen3-coder-480b
    apiBase: http://127.0.0.1:9099/v1
    apiKey: oracle-local
    roles: [chat, edit, apply]
  - name: Fast lane (local)
    provider: openai
    model: qwen3-coder-30b
    apiBase: http://127.0.0.1:9099/v1
    apiKey: oracle-local
    roles: [chat, autocomplete]
  - name: Embeddings (local)
    provider: openai
    model: qwen3-embedding-4b
    apiBase: http://127.0.0.1:9099/v1
    apiKey: oracle-local
    roles: [embed]
'@ | Set-Content -Path (Join-Path $cont "config.yaml")
        Write-Host "==> wrote $cont\config.yaml"
        # NOTE: model names above are the full-profile tiers; on reduced profiles
        # llama-swap simply won't have the big ones - pick the model that exists
        # from Continue's model dropdown (e.g. qwen2.5-coder-7b on micro).
        $tiers = Join-Path $Root "serving\tiers.env"
        if (Test-Path $tiers) {
            $sonnet = (Get-Content $tiers | Where-Object { $_ -like "SONNET_MODEL=*" }) -replace "SONNET_MODEL=", ""
            $haiku = (Get-Content $tiers | Where-Object { $_ -like "HAIKU_MODEL=*" }) -replace "HAIKU_MODEL=", ""
            if ($sonnet) {
                (Get-Content (Join-Path $cont "config.yaml")) `
                    -replace "model: qwen3-coder-480b", "model: $sonnet" `
                    -replace "model: qwen3-coder-30b", "model: $haiku" |
                    Set-Content (Join-Path $cont "config.yaml")
                Write-Host "==> Continue models remapped to this machine's profile ($sonnet / $haiku)"
            }
        }
        # VSCodium user settings: telemetry/updates off
        $userDir = Join-Path $env:APPDATA "VSCodium\User"
        New-Item -ItemType Directory -Force -Path $userDir | Out-Null
        $settings = Join-Path $userDir "settings.json"
        if (-not (Test-Path $settings)) {
            @'
{
  "telemetry.telemetryLevel": "off",
  "update.mode": "none",
  "extensions.autoUpdate": false,
  "extensions.autoCheckUpdates": false,
  "workbench.colorTheme": "Default Dark Modern",
  "editor.inlineSuggest.enabled": true,
  "continue.enableTabAutocomplete": true
}
'@ | Set-Content -Path $settings
            Write-Host "==> wrote VSCodium settings (telemetry off, updates off)"
        }
        Write-Host ""
        Write-Host "IDE ready. One-time Roo Code setup (stores its own config):"
        Write-Host "  panel -> settings -> API Provider: OpenAI Compatible"
        Write-Host "  Base URL: http://127.0.0.1:9099/v1   API Key: oracle-local"
        Write-Host "  Model: (whatever your profile serves - see Models tab in oracle desk)"
        Write-Host "Launch with: bin\oracle.ps1 ide"
    }
    "launch" {
        $codium = Find-Codium
        if (-not $codium) { Write-Host "IDE not installed - run: bin\oracle.ps1 ide install"; exit 1 }
        & $codium $Root
    }
    default { Write-Host "usage: setup-ide.ps1 {install|launch}" }
}
