#!/usr/bin/env bash
# Launch the Kilo engine, fully self-contained in this repo (mac twin).
# Kilo reads state/generated/kilo/kilo.jsonc, generated by sync-models.sh against
# llama-swap (openai-compatible provider, telemetry off, sharing off).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export ORACLE_ROOT="$ROOT"
# shellcheck source=/dev/null
source "$ROOT/engines/shared/lean-ctx-env.sh"
export UV_OFFLINE=1
export UV_CACHE_DIR="$ROOT/incoming/dependency-cache/uv"
export PATH="$ROOT/env/.venv/bin:$ROOT/.tools/bin:$ROOT/.tools/npm/bin:$PATH"
export KILO_CONFIG="$ROOT/state/generated/kilo/kilo.jsonc"
export OPENCODE_CONFIG="$KILO_CONFIG"
# hardening profile: disable every Kilo call-home path (telemetry, sharing,
# gateway, update, remote model discovery, ...). See engines/kilo/HARDENING.md.
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/hardened-env.sh"

command -v kilo >/dev/null || { echo "ERROR: kilo not installed — run 'make install'"; exit 1; }
bash "$ROOT/connectors/ide/sync-models.sh" >/dev/null
[[ -f "$KILO_CONFIG" ]] || {
  echo "ERROR: generated Kilo config is unavailable; install a validated model snapshot" >&2
  exit 1
}
curl -sf -m 5 "http://127.0.0.1:9099/health" >/dev/null 2>&1 \
  || echo "WARN: llama-swap not responding — run 'oracle serve'" >&2

exec kilo "$@"
