#!/usr/bin/env bash
# Launch the Kilo engine, fully self-contained in this repo (mac twin).
# Kilo reads ~/.config/kilo/kilo.jsonc, generated by sync-models.sh against
# llama-swap (openai-compatible provider, telemetry off, sharing off).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export ORACLE_ROOT="$ROOT"
export PATH="$ROOT/.tools/npm/bin:$PATH"

command -v kilo >/dev/null || { echo "ERROR: kilo not installed — run 'make install'"; exit 1; }
[[ -f "$HOME/.config/kilo/kilo.jsonc" ]] || bash "$ROOT/connectors/ide/sync-models.sh" >/dev/null
curl -sf -m 5 "http://127.0.0.1:9099/health" >/dev/null 2>&1 \
  || echo "WARN: llama-swap not responding — run 'oracle serve'" >&2

exec kilo "$@"
